<div class="xrx-news-category xrx-<?= $t['_align'] ?>">
	<h3><?= $tm->_('categories', '.news') ?></h3>
	<?= $slots['categories'] ?>
</div>

<? if ($t['news']): ?>
	<ul class="xrx-news-list-<?= $t['_xalign'] ?>">
	<? foreach ($t['news'] as $news): ?>
		<li class="xrx-news-content">
			<h2><a href="<?= $ro->gen('default', array('path'=>'news/view', 'id'=>$news->id, 'title'=>$news->title)) ?>"><?= $news->title ?></a></h2>
			<small><?= sprintf($tm->_('written by %s in %s'), $news->username, $news->category_name) ?></small><br />
			<small><?= $tm->_d($t['news']->date) ?></small>
			
			<div class="xrx-news-entry">
				<? if ($news->image): ?>
					<img class="xrx-thumbnail-60 xrx-<?= $t['_align'] ?>" src="<?= $news->image ?>" />
				<? endif; ?>
				<?= ($news->summary) ? $news->summary : $news->content; ?>
			</div>
		</li>
	<? endforeach; ?>
	</ul>
<? else: ?>
	<p><?= $tm->_("there's no news available for current language", '.news') ?></p>
<? endif; ?>


<div class="xrx-list-nav">
	<div class="xrx-pagination xrx-right"><? $vw->paginator($t['page'], $t['total'], $t['limit']) ?></div>
</div>