<?php
// Create links to other languages' translation
if ( isset($t['translations']) ) {
	foreach ($t['translations'] as $tl) {
		$links[] = "<a href='" . $tl['link'] . "'>" . $tl['title'] . "</a>";
	}
}
?>

<? if ( isset($t['translations']) ) : ?>
	<div class="xrx-news-toolbox xrx-<?= $t['_xalign'] ?>">
		<?= sprintf($tm->_('this news also available in %s', '.news'), implode(' | ', $links)); ?>
	</div>
<? endif ?>

<h2><?= $t['news']->title ?></h2>

<small><?= sprintf($tm->_('written by %s in %s'), $t['news']->username, $t['news']->category_name) ?></small><br />
<small><?= $tm->_d($t['news']->date) ?></small>

<div class="xrx-news-entry">
	<? if ($t['news']->image): ?>
		<img class="xrx-<?= $t['_align'] ?>" src="/uploads/news/<?= $t['news']->image ?>" />
	<? endif; ?>
	<p><strong><?= $t['news']->summary ?></strong></p>
	<?= $t['news']->content ?>
</div>

<small><?= sprintf('last updated on %s', $tm->_d($t['news']->modified)) ?></small>

<div id="xrx-comments-list"><?= $slots['comments'] ?></div>

<? if ($t['news']->comment_status): ?>
	<div id="xrx-comment-form"><?= $slots['comment-form'] ?></div>
<? else: ?>
	<div id="xrx-comment-disabled" class="xrx-center-text"><?= $tm->_('sending comments on this news has been disabled') ?></div>
<? endif ?>