<?php
// Create links to other languages' translation
if ( isset($t['translations']) ) {
	foreach ($t['translations'] as $tl) {
		$links[] = "<a href='" . $tl['link'] . "'>" . $tl['title'] . "</a>";
	}
}
?>

<? if ( isset($t['translations']) ) : ?>
	<div class="xrx-news-toolbox xrx-<?= $t['_xalign'] ?>">
		<?= sprintf($tm->_('this news also available in %s', '.news'), implode(' | ', $links)); ?>
	</div>
<? endif ?>

<h2><?= $t['news']->title ?></h2>

<small><?= sprintf($tm->_('written by %s in %s'), $t['news']->username, $t['news']->category_name) ?></small><br />
<small><?= $tm->_d($t['news']->date) ?></small>

<div class="xrx-news-entry"><?= $t['news']->content ?></div>

<small><?= sprintf('last updated on %s', $tm->_d($t['news']->modified)) ?></small>