<script type="text/javascript">
	<!--
	$(document).ready( function() {
		// Handle fieldset checkboxes
		var checkBox = $('legend > input[type="checkbox"]');

		checkBox.each( function(idx, item) {
			if ($(item).attr('checked')) {
				$(item).parents('fieldset')
					   .children('ol')
					   .slideDown();
			}
		})

		checkBox.click( function() {
			$(this).parents('fieldset')
				   .children('ol')
				   .slideToggle( checkBox.attr('checked') );
		})


		// Handle "Delete Translation" buttons
		var btnDelete = $('.xrx-news-delete');

		btnDelete.click( function() {
			if ( confirm("<?= $tm->_('are you sure?', '.news')?>")) {
				var lang = this.id.split('-')[3];
				$('#xrx-news-fieldset-' + lang).remove();
				$('form').append('<input type="hidden" name="deleted[]" value="' + lang + '"');
			}
		})

		// Image Field
		$('#xrx-news-browse').click( function() {
			var finder = new CKFinder() ;
			finder.BasePath = '/scripts/ckfinder/';
			finder.SelectFunction = cbSelect;
			finder.Popup();
		});
	})

	function cbSelect(p) { document.getElementById('xrx-news-image').value = p };
	// -->
</script>



<form action="<?= $ro->gen(null); ?>" method="post">
	<?php foreach ($t['locales'] as $locale): ?>
	<fieldset id="xrx-news-fieldset-<?= $locale->lang ?>" dir="<?= $locale->dir ?>">
		<legend>
			<? if ($locale->id == $t['currentLocale']): ?>
				<?= $tm->_('edit news', '.news') ?>
				<input type="checkbox" class="xrx-hidden" name="<?= "translation[$locale->lang][check]" ?>" checked="checked" />
			<? else: ?>
				<input type="checkbox" id="xrx-news-translation-<?= $locale->lang ?>" class="xrx-pointer" name="<?= "translation[$locale->lang][check]" ?>" <? if (isset($t['news'][$locale->lang])): ?>checked="checked"<? endif ?> />
				<label for="xrx-news-translation-<?= $locale->lang ?>" class="xrx-pointer"><?= sprintf($tm->_('translate to %s', '.news', $locale->id), $locale->desc) ?></label>
			<? endif; ?>
		</legend>
		<ol <?= ( $locale->id == $t['currentLocale'] || isset($t['news'][$locale->lang]) ) ? '' : 'class="xrx-hidden"' ?>>
			<li>
				<label for="xrx-news-title-<?= $locale->lang ?>"><?= $tm->_('title', '.news', $locale->id) ?><em class="xrx-required">*</em></label>
				<input type="text" id="xrx-news-title-<?= $locale->lang ?>" class="xrx-news-title" name="<?= "translation[$locale->lang][title]" ?>" value="<?= $t['news'][$locale->lang]->title ?>" maxlength="200" />
			</li>
			<li>
				<label for="xrx-news-summary-<?= $locale->lang ?>"><?= $tm->_('summary', '.news', $locale->id) ?></label>
				<textarea id="xrx-news-summary-<?= $locale->lang ?>" class="xrx-news-summary" name="<?= "translation[$locale->lang][summary]" ?>"><?= $t['news'][$locale->lang]->summary ?></textarea>
			</li>
			<li>
				<label for="xrx-news-content-<?= $locale->lang ?>"><?= $tm->_('content', '.news', $locale->id) ?><em class="xrx-required">*</em></label>
				<textarea id="xrx-news-content-<?= $locale->lang ?>" name="<?= "translation[$locale->lang][content]" ?>"><?= $vw->escape($t['news'][$locale->lang]->content) ?></textarea>
				<script type="text/javascript">
					<!--
					var cke = CKEDITOR.replace('xrx-news-content-<?= $locale->lang ?>', {
						language: '<?= $locale->lang ?>',
						contentsLangDirection: '<?= $locale->dir ?>'
					});

					CKFinder.SetupCKEditor(cke, '/scripts/ckfinder/');
					// -->
				</script>
			</li>
			<? if ($locale->id == $t['currentLocale']): ?>
			<li>
				<label for="xrx-news-image"><?= $tm->_('image', '.news') ?></label>
				<? if (empty ($t['news'][$t['_language']]->image)): ?>
					<input id="xrx-news-image" type="text" name="image" readonly="readonly" />
					<input id="xrx-news-browse" type="button" value="<?= $tm->_('browse', '.news') ?>" />
				<? else: ?>
					<img class="xrx-thumbnail-40" src="<?= $t['news'][$t['_language']]->image ?>" />
				<? endif; ?>
			</li>
			<li>
				<label for="xrx-news-date"><?= $tm->_('date', '.news') ?><em class="xrx-required">*</em></label>
				<input type="text" id="xrx-news-date" name="date" value="<?= $t['news'][$locale->lang]->date ?>" maxlength="20">
					<img src="scripts/JalaliJSCalendar/examples/cal.png" id="xrx-news-cal-trigger" title="<?= $tm->_('date selector', '.news'); ?>" alt="<?= $tm->_('date selector', '.news'); ?>" />
				</input>
				<script type="text/javascript">
					<!--
					Calendar.setup({
						inputField: "xrx-news-date",
						showsTime: true,
						dateType: "<?= (isset ($t['jalali'])) ? 'jalali' : 'gregorian'; ?>",
						ifFormat: "<?= $t['dateFormat'] ?>",
						button: "xrx-news-cal-trigger"
					});
					// -->
				</script>
			</li>
			<li>
				<label for="xrx-news-category"><?= $tm->_('category', '.news') ?><em class="xrx-required">*</em></label>
				<select id="xrx-news-category" name="category">
				<? foreach ($t['categories'] as $category): ?>
					<option value="<?= $category->id ?>"<? if ($t['news'][$t['_language']]->category_id == $category->id) echo 'selected="selected"' ?>>
						<?= str_repeat('&#160;&#160;&#160;', $category->depth - 1) . $category->name ?>
					</option>
				<? endforeach; ?>
				</select>
			</li>
			<li>
				<label><?= $tm->_('published', '.news') ?></label>
				
				<input id="xrx-news-published-yes" type="radio" name="published" value="1" <? if ($t['news'][$locale->lang]->published): ?>checked="checked"<? endif ?> />
				<label for="xrx-news-published-yes" class="xrx-label-radio"><?= $tm->_('yes', '.news') ?></label>

				<input id="xrx-news-published-no" type="radio" name="published" value="0" <? if (!$t['news'][$locale->lang]->published): ?>checked="checked"<? endif ?> />
				<label for="xrx-news-published-no" class="xrx-label-radio"><?= $tm->_('no', '.news') ?></label>
			</li>
			<li>
				<label><?= $tm->_('allow comments', '.news') ?></label>
				
				<input id="xrx-news-comments-yes" type="radio" name="comments" value="1" <? if ($t['news'][$locale->lang]->comment_status): ?>checked="checked"<? endif ?> />
				<label for="xrx-news-comments-yes" class="xrx-label-radio"><?= $tm->_('yes', '.news') ?></label>

				<input id="xrx-news-comments-no" type="radio" name="comments" value="0" <? if (!$t['news'][$locale->lang]->comment_status): ?>checked="checked"<? endif ?> />
				<label for="xrx-news-comments-no" class="xrx-label-radio"><?= $tm->_('no', '.news') ?></label>
			</li>
			<? else: ?>
			<? if ($locale->translated): ?>
			<li>
				<button type="button" id="xrx-news-delete-<?= $locale->lang ?>" class="xrx-news-delete"><?= sprintf($tm->_('delete %s translation', '.news', $locale->lang), $locale->desc) ?></button>
			</li>
			<? endif; ?>
			<? endif; ?>
		</ol>
	</fieldset>
	<?php endforeach; ?>
	
	<input type="hidden" name="id" value="<?= $t['news'][$t['_language']]->id ?>" />
	<input type="submit" value="<?= $tm->_('submit', '.news'); ?>" />
	<a href="<?= $ro->gen('default', array('path' => 'admin/news')) ?>">
		<input type="button" value="<?= $tm->_('cancel', '.news'); ?>" />
	</a>
</form>