<script type="text/javascript">
	<!--
	$(document).ready( function() {
		// Check All Handler
		$('.xrx-check-all').click( function() {
			$('.xrx-check-column').children().attr('checked', $(this).attr('checked'));
		})

		// Delete Button Handler
		$('.xrx-delete-button').click( function(e) {
			var valid = false;

			$('td.xrx-check-column').children().each( function(idx, el) {
				if ($(el).attr('checked')) {
					valid = true;
					return;
				}
			})

			if (! valid) {
				alert('<?= $tm->_('please select a category.', '.category') ?>');
				e.preventDefault();
				return false;
			}

			// Sure?
			if (! confirm('<?= $tm->_('are you sure?', '.category') ?>')) {
				e.preventDefault();
			}
		})
	})
	// -->
</script>


<h2>
	<img class="xrx-icon-32" src="/images/category/category-32.png" alt="<?= $tm->_('category list', '.category'); ?>" /><?= $tm->_('category list', '.category'); ?>
</h2>

<form action="<?= $ro->gen('default', array('path' => 'admin/category/delete')) ?>" method="post">
	<table class="xrx-table-list">
		<thead>
			<tr class="xrx-<?= $t['_align']; ?>-text">
				<th class="xrx-check-column"><input type="checkbox" class="xrx-check-all" /></th>
				<th class="xrx-title-column"><?= $tm->_('name', '.category') ?></th>
				<th><?= $tm->_('modules', '.category') ?></th>
			</tr>
		</thead>
		<tfoot>
			<tr class="xrx-<?= $t['_align']; ?>-text">
				<th class="xrx-check-column"><input type="checkbox" class="xrx-check-all" /></th>
				<th class="xrx-title-column"><?= $tm->_('name', '.category') ?></th>
				<th><?= $tm->_('modules', '.category') ?></th>
			</tr>
		</tfoot>
		<tbody>
		<? if ( count ($t['categories']) > 0 ): ?>
			<? foreach ($t['categories'] as $category): ?>
			<tr>
				<td class="xrx-check-column">
				<? if ($category->id != 1): ?>
					<input type="checkbox" name="id[]" value="<?= $category->id ?>" />
				<? endif ?>
				</td>
				<td class="xrx-title-column">
					<a href="<?= $ro->gen('default', array('path'=>'admin/category/edit', 'id'=>$category->id)) ?>" title="<?= sprintf($tm->_('edit \'%s\'', '.category'), $category->name) ?>">
						<?= @str_repeat('— ', $category->depth - 1) . $category->name ?>
					</a>
				</td>
				<td>
				<? if (empty ($category->modules)): ?>
					<span class="xrx-italic-text">.</span>
				<? else: ?>
					<? $link = array() ?>

					<? foreach ($category->modules as $id => $module): ?>
						<? $link[] = $module ?>
					<? endforeach ?>

					<?= implode(', ', $link) ?>
				<? endif ?>
				</td>
			</tr>
			<? endforeach; ?>
		<? else: ?>
			<tr>
				<td colspan="3" class="xrx-center-text xrx-italic-text"><?= $tm->_("There's no category.", '.category') ?></td>
			</tr>
		<? endif ?>
		</tbody>
	</table>

	<input type="submit" class="xrx-button xrx-delete-button" value="<?= $tm->_('delete', '.category') ?>" />
</form>