<div id="xrx-footer">
	<div class="xrx-inside">
		<? if ($us->isAuthenticated()): ?>
		<div class="xrx-logged-box xrx-<?= $t['_xalign'] ?>">
			<?= $tm->_('you are logged in.', '.widgets'); ?>
			<a href="<?= $ro->gen('default', array('module'=>'user', 'action'=>'logout')); ?>"><?= $tm->_('log out', '.widgets'); ?></a>
		</div>
		<? endif; ?>
		
		<p>
			<?= sprintf($tm->_('copyright © 2009-%s khashayar hajian.', '.widgets'), date('Y')) ?><br />
			<?= $tm->_('powered by xrx content management system.', '.widgets') ?>
		</p>
	</div>
</div>
