<div id="xrx-navigation">
	<ul>
		<li class="xrx-<?= $t['_align'] ?>"><a href="<?= $ro->gen('index'); ?>"><?= $tm->_('home', '.widgets') ?></a></li>

		<? if ($t['showOnFront'] != 'news'): ?>
			<li class="xrx-<?= $t['_align'] ?>"><a href="<?= $ro->gen('default', array('path' => 'news')); ?>"><?= $tm->_('news', '.widgets') ?></a></li>
		<? endif; ?>

		<? if ($t['pages']): ?>
			<? foreach ($t['pages'] as $page): ?>
				<? if ($t['showOnFront'] != 'page' || $t['showOnFrontId'] != $page->id): ?>
					<li class="xrx-<?= $t['_align'] ?>"><a href="<?= $ro->gen('default', array('path' => 'page', 'id' => $page->id)); ?>"><?= $page->title ?></a></li>
				<? endif; ?>
			<? endforeach; ?>
		<? endif; ?>

		<? foreach ($tm->getAvailableLocales() as $lc): ?>
			<? if ($lc['identifier'] != $tm->getCurrentLocaleIdentifier()): ?>
				<? $href = $ro->gen(null, array('locale' => $lc['identifier'])); ?>
				<? $desc = $lc['parameters']['description']; ?>
				<li class="xrx-<?= $t['_xalign'] ?>"><a href='<?= $href ?>'><?= $desc ?></a></li>
			<? endif; ?>
		<? endforeach; ?>
	</ul>
</div>

		<!--
		<div class="xrx-date xrx-<?= $t['_xalign'] ?>">
			<p><?= $tm->_d(time()); ?></p>
		</div>
		-->

<div class="xrx-clear"></div>

<div id="xrx-header">
	<div class="xrx-inside">
		<h1 id="xrx-logo" class="xrx-<?= $t['_align'] ?>">
			<a href="<?= $ro->getBaseHref(); ?>" title="<?= $tm->_('main page', '.widgets') ?>"><img src="/themes/khashayar/images/xerxes.png" alt="khashayar" /></a>
			<!--<a href="<?= $ro->getBaseHref(); ?>" title="<?= $tm->_('main page', '.widgets') ?>"><?= $us->getAttribute('website_title', 'setting.general') ?></a>-->
		</h1>

		<p class="xrx-date xrx-<?= $t['_xalign'] ?>"><?= $tm->_d(time()); ?></p>
		<p id="xrx-description">“Creativity, individuality and flexibility have always been the driving force behind my development and services. In this blog you will find information about my online projects, services and references. Furthermore, I inform you on current trends in the field of web development.”</p>

		<!--
		<?php
		foreach ($tm->getAvailableLocales() as $lc) {
			$href = $ro->gen(null, array('locale' => $lc['identifier']));
			$flag = $lc['identifierData']['territory'];
			$desc = $lc['parameters']['description'];
			echo "<a class='xrx-language-flag xrx-pointer' href='$href'><img src='/images/flags/$flag.png' title='$desc' alt='$desc' /></a>";
		}
		?>
		-->
	</div>
</div>

