<h3><?= $tm->_('comments', '.comment') ?></h3>
<div class="xrx-comment-meta">
	<?= sprintf($tm->_('%s comment(s).', '.comment'), count($t['comments'])) ?>
	<a href="#xrx-comment-form"><?= $tm->_('leave a comment.', '.comment') ?></a>
</div>

<? if (isset ($t['comments'])): ?>
	<ol>
	<? foreach ($t['comments'] as $comment): ?>
		<li id="xrx-comment-<?= $comment->getId() ?>">
			<h5>
				<? if ($comment->getAuthorUrl()): ?>
				<a href="<?= $comment->getAuthorUrl() ?>" title="<?= $comment->getAuthorUrl() ?>"
				   target="_blank"><?= $comment->getAuthorName() ?></a>
				<? else: ?>
					<?= $comment->getAuthorName() ?>
				<? endif; ?>
			</h5>
			<small><?= $tm->_d($comment->getDate()) ?></small>
			<p><?= $vw->escape($comment->getContent()) ?></p>
		</li>
	<? endforeach; ?>
	</ol>
<? else: ?>
	<div><?= $tm->_("there's no comments", ".comment") ?></div>
<? endif; ?>