<div id="xrx-header">
	<h1 class="xrx-<?= $t['_align']; ?>">
		<a href="<?= $ro->gen('index'); ?>" title="<?= $tm->_('visit site', '.widgets'); ?>"><?= $us->getAttribute('website_title', 'setting.general') . " " . $tm->_('administration area', '.widgets'); ?></a>

		<?php
		foreach ($tm->getAvailableLocales() as $lc) {
			$href = $ro->gen(null, array('locale' => $lc['identifier']));
			$flag = $lc['identifierData']['territory'];
			$desc = $lc['parameters']['description'];
			echo "<a class='xrx-language-flag xrx-pointer' href='$href'><img src='/images/flags/$flag.png' title='$desc' alt='$desc' /></a>";
		}
		?>
	</h1>

	<div id="xrx-date-<?= $t['_xalign']; ?>"><?= $tm->_d(time()); ?></div>

	<div id="xrx-user-info" class="xrx-<?= $t['_xalign']; ?>">
		<p>
			<?php

			$user	= sprintf('<a href="%s" title="%s">%s</a>',
						$ro->gen("default", array("path" => "user/index")),
						$tm->_("edit your profile", ".widgets"),
						$us->getAttribute('username'));

			$logout = sprintf('<a href="%s" title="%s">%s</a>',
						$ro->gen('default', array("path" => "user/logout")),
						$tm->_('log out', '.widgets'),
						$tm->_('log out', '.widgets'));
			?>

			<?= sprintf($tm->_('you are logged in as %s', '.widgets'), $user); ?> | <?= $logout ?>
		</p>
	</div>
</div>