<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $t['_language']; ?>" lang="<?= $t['_language']; ?>" dir="<?= $t['_dir']; ?>">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="refresh" content="3;URL=<?= $t['_url']; ?>" />

		<base href="<?= $ro->getBaseHref(); ?>" />
		<title><?php if(isset($t['_title'])) echo htmlspecialchars($t['_title']) . ' - '; echo AgaviConfig::get('core.app_name'); ?></title>
		
		<!-- Cascading Style Sheets -->
		<link rel="stylesheet" type="text/css" href="templates/default/styles/redirect.css" media="screen" />
	</head>

	<body>
		<div id="xrx-message" class="xrx-<?= (isset($t['_type']) ? $t['_type'] : 'info') ?>">
			<?= $inner; ?>
		</div>
	</body>
</html>
