<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $t['_language']; ?>" lang="<?php echo $t['_language']; ?>" dir="<?php echo $t['_dir']; ?>">
	<head>
		<base href="<?= $ro->getBaseHref(); ?>" />
		<title><?php if (isset($t['_title'])) echo $vw->escape($t['_title']) . ' - '; echo $us->getAttribute('website_title', 'setting.general'); ?></title>

		<meta http-equiv="Content-Type" content="<?php echo $container->getOutputType()->getParameter('http_headers[Content-Type]', 'text/html; charset=utf-8'); ?>" />
		<meta http-equiv="Content-Style-Type" content="text/css" />
		<meta http-equiv="Content-Script-Type" content="text/javascript" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<meta name="robots" content="index,follow" />

		<!-- Cascading Style Sheets -->
		<!--<link rel="stylesheet" type="text/css" href="templates/khashayar/styles/reset.css" media="all" />-->
		<!--<link rel="stylesheet" type="text/css" href="templates/khashayar/styles/master.css" media="screen" />-->
		<link rel="stylesheet" type="text/css" href="templates/khashayar/styles/frontend.css" media="screen" />

		<!-- Javascript -->
		<script type="text/javascript" src="/scripts/jQuery/jquery.js"></script>

		<!-- Fav Icon -->
		<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
	</head>

	<body class="<?php echo $t['_dir']; ?>">

		<?php echo $slots['header']; ?>

		<div id="xrx-container">
			<div class="xrx-inside">
				<?php echo $inner; ?>
			</div>
		</div>

		<?php echo $slots['footer']; ?>

	</body>
</html>