<div id="xrx-footer">
	<div class="xrx-wrapper">
		<? if ($us->isAuthenticated()): ?>
		<div class="xrx-<?= $t['_xalign'] ?>">
			<?= $tm->_('You are logged in.', '.widgets'); ?>
				<a href="<?= $ro->gen('default', array('module'=>'user', 'action'=>'logout')); ?>">
					<?= $tm->_('Log Out', '.widgets'); ?>
				</a>
		</div>
		<? endif; ?>
		
		<p>Copyright © 2009-2010 XRX Content Management System</p>
	</div>
</div>
