<div id="xrx-header">
	<div class="xrx-inside">
		<div class="xrx-date xrx-<?= $t['_xalign'] ?>">
			<p><?= $tm->_d(time()); ?></p>
		</div>

		<h1 id="xrx-logo">
			<a href="<?= $ro->getBaseHref(); ?>" title="<?= $tm->_('main page', '.widgets') ?>"><?= $us->getAttribute('website_title', 'setting.general') ?></a>

			<?php
			foreach ($tm->getAvailableLocales() as $lc) {
				$href = $ro->gen(null, array('locale' => $lc['identifier']));
				$flag = $lc['identifierData']['territory'];
				$desc = $lc['parameters']['description'];
				echo "<a class='xrx-language-flag xrx-pointer' href='$href'><img src='/images/flags/$flag.png' title='$desc' alt='$desc' /></a>";
			}
			?>
		</h1>
	</div>
</div>

<div id="xrx-menu">
	<div class="xrx-inside">
		<ul class="xrx-<?= $t['_align'] ?>">
			<li><a href="<?= $ro->gen('index'); ?>"><?= $tm->_('home', '.widgets') ?></a></li>
			
			<? if ($t['showOnFront'] != 'news'): ?>
				<li><a href="<?= $ro->gen('default', array('path' => 'news')); ?>"><?= $tm->_('news', '.widgets') ?></a></li>
			<? endif; ?>

			<? if ($t['pages']): ?>
				<? foreach ($t['pages'] as $page): ?>
					<? if ($t['showOnFront'] != 'page' || $t['showOnFrontId'] != $page->id): ?>
						<li><a href="<?= $ro->gen('default', array('path' => 'page', 'id' => $page->id)); ?>"><?= $page->title ?></a></li>
					<? endif; ?>
				<? endforeach; ?>
			<? endif; ?>
		</ul>
	</div>
</div>
