<div id="xrx-content" class="xrx-<?= $t['_align'] ?>">
	<? if ($t['news']): ?>
		<ul class="xrx-news-list">
		<? foreach ($t['news'] as $news): ?>
			<li id="xrx-news-<?= $news->id ?>" class="xrx-news-item">
				<div class="xrx-news-meta xrx-<?= $t['_align'] ?>">
					<?= $tm->_d($t['news']->date) ?><br />
					<a href="<?= $ro->gen('default', array('path'=>'news/index', 'category'=>$news->category_id)) ?>"><?= $news->category_name ?></a>
				</div>
				
				<h2><a href="<?= $ro->gen('default', array('path'=>'news/view', 'id'=>$news->id, 'title'=>$news->title)) ?>"><?= $news->title ?></a></h2>

				<div class="xrx-news-entry xrx-<?= $t['_xalign'] ?>">
					<? if ($news->image): ?><img class="xrx-thumbnail-60 xrx-<?= $t['_align'] ?>" src="/uploads/news/<?= $news->image ?>" /><? endif; ?>
					<?= ($news->summary) ? $news->summary : $news->content; ?>
				</div>

				<div class="xrx-clear"></div>
			</li>
		<? endforeach; ?>
		</ul>
	<? else: ?>
		<p><?= $tm->_("there's no news available for current language.", '.news') ?></p>
	<? endif; ?>


	<div class="xrx-list-nav">
		<div class="xrx-pagination"><? $vw->paginator($t['page'], $t['total'], $t['limit']) ?></div>
	</div>
</div>

<div id="xrx-sidebar" class="xrx-<?= $t['_xalign'] ?>">
	<div class="xrx-news-category">
		<h2><?= $tm->_('categories', '.news') ?></h2>
		<?= $slots['categories'] ?>
	</div>
</div>