<?php
// Create links to translation
if ( isset($t['translations']) ) {
	foreach ($t['translations'] as $tl) {
		$links[] = "<a href='" . $tl['link'] . "'>" . $tl['title'] . "</a>";
	}
}
?>

<? if ( isset($t['translations']) ) : ?>
	<div class="xrx-news-toolbox xrx-<?= $t['_xalign'] ?>">
		<?= sprintf($tm->_('this news also available in %s', '.news'), implode(' | ', $links)); ?>
	</div>
<? endif ?>


<div id="xrx-content" class="xrx-<?= $t['_align'] ?>">
	<div class="xrx-news-item">
		<h1><?= $t['news']->title ?></h1>

		<div class="xrx-news-meta-view">
			<small><?= $tm->_d($t['news']->date) ?></small><br />
			<small><?= sprintf($tm->_('category: %s', '.news'), '<strong><a href="' . $ro->gen('default', array('path'=>'news/index', 'category'=>$t['news']->category_id)) . '">' . $t['news']->category_name . '</a></strong>') ?></small>
		</div>
		<div class="xrx-news-entry-view">
			<p>
				<? if ($t['news']->image): ?>
					<img class="xrx-<?= $t['_align'] ?>" src="/uploads/news/<?= $t['news']->image ?>" />
				<? endif; ?>
				<strong><?= $t['news']->summary ?></strong>
			</p>
			<?= $t['news']->content ?>
		</div>

		<small><?= sprintf('last updated on %s', $tm->_d($t['news']->modified)) ?></small>
	</div>
</div>


<div id="xrx-sidebar" class="xrx-<?= $t['_xalign'] ?>">
	<div class="xrx-news-category">
		<h2><?= $tm->_('categories', '.news') ?></h2>
		<?= $slots['categories'] ?>
	</div>
</div>