<h3><?= $tm->_('comments', '.comment') ?></h3>

<? if (isset ($t['comments'])): ?>
	<ol>
	<? foreach ($t['comments'] as $comment): ?>
		<li id="xrx-comment-<?= $comment->getId() ?>">
			<h5>
				<? if ($comment->getAuthorUrl()): ?>
				<a href="<?= $comment->getAuthorUrl() ?>" title="<?= $comment->getAuthorUrl() ?>"
				   target="_blank"><?= $vw->escape($comment->getAuthorName()) ?></a>
				<? else: ?>
					<?= $vw->escape($comment->getAuthorName()) ?>
				<? endif; ?>
			</h5>
			<small><?= $tm->_d($comment->getDate()) ?></small>
			<p><?= $vw->escape($comment->getContent()) ?></p>
		</li>
	<? endforeach; ?>
	</ol>
<? else: ?>
	<div><?= $tm->_("there's no comments", ".comment") ?></div>
<? endif; ?>