<h3><?= $tm->_('comments', '.comment') ?></h3>

<? if (isset ($t['comments'])): ?>
	<ol>
	<? foreach ($t['comments'] as $comment): ?>
		<li id="xrx-comment-<?= $comment->getId() ?>">
			<h5>
				<a href="<?= $comment->getAuthorUrl() ?>" title="<?= $comment->getAuthorUrl() ?>" target="_blank">
					<?= $comment->getAuthorName() ?>
				</a>
			</h5>
			<small><?= $comment->getDate() ?></small>
			<p><?= $comment->getContent() ?></p>
		</li>
	<? endforeach; ?>
	</ol>
<? else: ?>
	<div><?= $tm->_("there's no comments", ".comment") ?></div>
<? endif; ?>