<script type="text/javascript">
	<!--
	$(document).ready( function() {
		var registered	= $('#xrx-comment-type-registered');
		var guest		= $('#xrx-comment-type-guest');

		registered.change( function() {
			$('#xrx-comment-name').hide();
			$('#xrx-comment-author-id').show();
		})

		guest.change( function() {
			$('#xrx-comment-name').show();
			$('#xrx-comment-author-id').hide();
		})
	})
	// -->
</script>


<form action="<?= $ro->gen(null); ?>" method="post">
	<fieldset>
		<legend><?= $tm->_('edit comment', '.comment') ?></legend>
		<ol>
			<li>
				<label><?= $tm->_('author type', '.comment') ?><em class="xrx-required">*</em></label>

				<input type="radio" id="xrx-comment-type-registered" name="author_type" value="registered" <? if ($t['comment']->user_type == 'registered'): ?>checked="checked"<? endif; ?> />
				<label for="xrx-comment-type-registered"><?= $tm->_('registered', '.comment') ?></label>

				<input type="radio" id="xrx-comment-type-guest" name="author_type" value="guest" <? if ($t['comment']->user_type == 'guest'): ?>checked="checked"<? endif; ?> />
				<label for="xrx-comment-type-guest"><?= $tm->_('guest', '.comment') ?></label>
			</li>
			<li>
				<label for="xrx-comment-name"><?= $tm->_('name', '.comment') ?><em class="xrx-required">*</em></label>
				<input type="text" id="xrx-comment-name" <? if ($t['comment']->user_type == 'registered'): ?>class="xrx-hidden"<? endif; ?> name="name" value="<?= $t['comment']->author_name ?>" maxlength="60" />
				<select id="xrx-comment-author-id" <? if ($t['comment']->user_type == 'guest'): ?>class="xrx-hidden"<? endif; ?> name="author_id">
				<? foreach ($t['users'] as $user): ?>
					<? $s = ($user->id == $t['comment']->author_id) ? ' selected="selected"' : '' ?>
					<option value="<?= $user->id ?>"<?= $s ?>><?= $user->username ?></option>
				<? endforeach; ?>
				</select>
			</li>
			<li>
				<label for="xrx-comment-email"><?= $tm->_('email', '.comment') ?><em class="xrx-required">*</em></label>
				<input type="text" id="xrx-comment-email" name="email" value="<?= $t['comment']->author_email ?>" maxlength="100" />
			</li>
			<li>
				<label for="xrx-comment-url"><?= $tm->_('website', '.comment') ?></label>
				<input type="text" id="xrx-comment-url" name="url" value="<?= $t['comment']->author_url ?>" maxlength="200" />
			</li>
			<li>
				<label for="xrx-comment-date"><?= $tm->_('date', '.comment') ?><em class="xrx-required">*</em></label>
				<input type="text" id="xrx-comment-date" name="date" value="<?= $t['comment']->date ?>" maxlength="20" />
			</li>
			<li>
				<label><?= $tm->_('status', '.comment') ?></label>

				<input type="radio" id="xrx-comment-status-pending" name="status" value="pending" <? if ($t['comment']->status == 'pending'): ?>checked="checked"<? endif; ?> />
				<label for="xrx-comment-status-pending"><?= $tm->_('pending', '.comment') ?></label>
				
				<input type="radio" id="xrx-comment-status-approved" name="status" value="approved" <? if ($t['comment']->status == 'approved'): ?>checked="checked"<? endif; ?> />
				<label for="xrx-comment-status-approved"><?= $tm->_('approved', '.comment') ?></label>

				<input type="radio" id="xrx-comment-status-rejected" name="status" value="rejected" <? if ($t['comment']->status == 'rejected'): ?>checked="checked"<? endif; ?> />
				<label for="xrx-comment-status-rejected"><?= $tm->_('rejected', '.comment') ?></label>
			</li>
			<li>
				<label for="xrx-comment-content"><?= $tm->_('comment', '.comment') ?><em class="xrx-required">*</em></label>
				<textarea id="xrx-comment-content" name="content"><?= $t['comment']->content ?></textarea>
			</li>
		</ol>
	</fieldset>

	<input type="hidden" name="id" value="<?= $t['comment']->id ?>" />
	<input type="hidden" name="referer" value="<?= $t['referer'] ?>" />
	<input type="submit" value="<?= $tm->_('submit', '.comment'); ?>" />
	<a href="<?= $ro->gen('default', array('path' => 'admin')) ?>">
		<input type="button" value="<?= $tm->_('cancel', '.comment'); ?>" />
	</a>
</form>