<script type="text/javascript">
	<!--
	$(document).ready( function() {
		// Check All Handler
		$('.xrx-check-all').click( function() {
			$('.xrx-check-column').children().attr('checked', $(this).attr('checked'));
		})

		// Delete Button Handler
		$('.xrx-delete-button').click( function(e) {
			var valid = false;

			$('td.xrx-check-column').children().each( function(idx, el) {
				if ($(el).attr('checked')) {
					valid = true;
					return;
				}
			})

			if (! valid) {
				alert('<?= $tm->_('please select a comment.', '.comment') ?>');
				e.preventDefault();
				return false;
			}

			// Sure?
			if (! confirm('<?= $tm->_('are you sure?', '.comment') ?>')) {
				e.preventDefault();
			}
		})
	})
	// -->
</script>


<h2>
	<img class="xrx-icon-32" src="/images/comment/comment-32.png" alt="<?= $tm->_('comment list', '.comment'); ?>" /><?= $tm->_('comment list', '.comment'); ?>
</h2>

<form action="<?= $ro->gen('default', array('path' => 'admin/comment/delete')) ?>" method="post">
	<table class="xrx-table-list">
		<thead>
			<tr class="xrx-<?= $t['_align']; ?>-text">
				<th class="xrx-check-column"><input type="checkbox" class="xrx-check-all" /></th>
				<th class="xrx-title-column"><?= $tm->_('comment', '.comment') ?></th>
				<th><?= $tm->_('author', '.comment') ?></th>
				<th><?= $tm->_('date', '.comment') ?></th>
				<th><?= $tm->_('owner', '.comment') ?></th>
				<th><?= $tm->_('module', '.comment') ?></th>
			</tr>
		</thead>
		<tfoot>
			<tr class="xrx-<?= $t['_align']; ?>-text">
				<th class="xrx-check-column"><input type="checkbox" class="xrx-check-all" /></th>
				<th class="xrx-title-column"><?= $tm->_('comment', '.comment') ?></th>
				<th><?= $tm->_('author', '.comment') ?></th>
				<th><?= $tm->_('date', '.comment') ?></th>
				<th><?= $tm->_('owner', '.comment') ?></th>
				<th><?= $tm->_('module', '.comment') ?></th>
			</tr>
		</tfoot>
		<tbody>
		<? if ( count ($t['comments']) > 0 ): ?>
			<? foreach ($t['comments'] as $comment): ?>
			<tr>
				<td class="xrx-check-column"><input type="checkbox" name="id[]" value="<?= $comment->id ?>" /></td>
				<td class="xrx-title-column">
					<a href="<?= $ro->gen('default', array('path'=>'admin/comment/edit', 'id'=>$comment->id)) ?>"
					   title="<?= sprintf($tm->_('edit \'%s\'', '.comment'), $comment->content) ?>"><?= $comment->content ?></a>
				</td>
				<td><?= $comment->author_name ?></td>
				<td><?= $comment->date ?></td>
				<td><?= $comment->owner_title ?></td>
				<td><?= $comment->module ?></td>
			</tr>
			<? endforeach; ?>
		<? else: ?>
			<tr>
				<td colspan="6" class="xrx-center-text xrx-italic-text"><?= $tm->_("There's no comment.", '.comment') ?></td>
			</tr>
		<? endif ?>
		</tbody>
	</table>

	<input type="submit" class="xrx-button xrx-delete-button" value="<?= $tm->_('delete', '.comment') ?>" />
</form>