<h2>
	<img class="xrx-icon-32" src="/images/user/user-16.png" alt="<?= $tm->_('users list', '.user'); ?>" /><?= $tm->_('users list', '.user'); ?>
</h2>

<form action="<?= $ro->gen('default', array('path' => 'admin/user/delete')) ?>" method="post">
	<table class="xrx-table-list">
		<thead>
			<tr class="xrx-<?= $t['_align']; ?>-text">
				<th class="xrx-check-column"><input type="checkbox" class="xrx-check-all" /></th>
				<th class="xrx-title-column"><?= $tm->_('title', '.user') ?></th>
				<th><?= $tm->_('category', '.user') ?></th>
				<th><?= $tm->_('date', '.user') ?></th>
				<th><?= $tm->_('author', '.user') ?></th>
				<th><?= $tm->_('published', '.user') ?></th>
			</tr>
		</thead>
		<tfoot>
			<tr class="xrx-<?= $t['_align']; ?>-text">
				<th class="xrx-check-column"><input type="checkbox" class="xrx-check-all" /></th>
				<th class="xrx-title-column"><?= $tm->_('title', '.user') ?></th>
				<th><?= $tm->_('category', '.user') ?></th>
				<th><?= $tm->_('date', '.user') ?></th>
				<th><?= $tm->_('author', '.user') ?></th>
				<th><?= $tm->_('published', '.user') ?></th>
			</tr>
		</tfoot>
		<tbody>
		<? if ( count ($t['news']) > 0 ): ?>
			<? foreach ($t['news'] as $news): ?>
			<tr title="<?= strip_tags($news->content); ?>">
				<td class="xrx-check-column"><input type="checkbox" name="id[]" value="<?= $news->id ?>" /></td>
				<td class="xrx-title-column">
					<a href="<?= $ro->gen('default', array('path'=>'admin/news/edit', 'id'=>$news->id)) ?>"
					   title="<?= sprintf($tm->_('edit \'%s\'', '.user'), $news->title) ?>"><?= $news->title ?></a>
				</td>
				<td>
					<a href="<?= $ro->gen('default', array('path'=>'admin/category/edit', 'id'=>$news->category_id)) ?>"
					   title="<?= sprintf($tm->_('edit \'%s\'', '.user'), $news->category_name) ?>"><?= $news->category_name ?></a>
				</td>
				<td><?= $tm->_d($news->date) ?></td>
				<td><a href="<?= $ro->gen('default', array('path'=>'user/edit', 'id'=>$news->author_id)) ?>"><?= $news->username ?></a></td>
				<td><?= $news->published ? $tm->_('yes', '.user') : $tm->_('no', '.user'); ?></td>
			</tr>
			<? endforeach; ?>
		<? else: ?>
			<tr>
				<td colspan="5" class="xrx-center-text xrx-italic-text"><?= $tm->_("there's no user.", '.user') ?></td>
			</tr>
		<? endif ?>
		</tbody>
	</table>

	<input type="submit" class="xrx-button xrx-delete-button" value="<?= $tm->_('delete', '.user') ?>" />
</form>